import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layouts/sidebar";
import Rightbar from "@/components/layouts/rightbar";

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="flex min-h-screen pt-10">
          <Sidebar />
          <section className="flex-1">{children}</section>
          <Rightbar />
        </main>
      </body>
    </html>
  );
}
